on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
    
      # Runs the bicep CLI action - recursive + wildcard
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          files: '**/*.bicep'

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
